/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jpou_ffmpeg_Transcoding */

#ifndef _Included_com_jpou_ffmpeg_Transcoding
#define _Included_com_jpou_ffmpeg_Transcoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jpou_ffmpeg_Transcoding
 * Method:    startTrans
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jpou_ffmpeg_Transcoding_startTrans
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
